-- Setup curated Census views aggregating block group data to state and county level
-- Co-authored with CoCo

-- NOTE: Column names in the source tables are mixed-case and must be double-quoted.
-- Run this script in Snowflake with ACCOUNTADMIN role.

CREATE DATABASE IF NOT EXISTS CENSUS_AGENT;
USE DATABASE CENSUS_AGENT;
CREATE SCHEMA IF NOT EXISTS PUBLIC;
USE SCHEMA PUBLIC;

------------------------------------------------------------
-- V_POPULATION: Population demographics by state and county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_POPULATION AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
combined AS (
    SELECT
        LEFT(p.CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS,
        SUBSTR(p.CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        p."B01001e1" AS TOTAL_POPULATION,
        p."B01001e2" AS MALE_POPULATION,
        p."B01001e26" AS FEMALE_POPULATION,
        (p."B01001e3" + p."B01001e4" + p."B01001e5" + p."B01001e6" + COALESCE(p."B01001e27",0) + COALESCE(p."B01001e28",0) + COALESCE(p."B01001e29",0) + COALESCE(p."B01001e30",0)) AS POP_UNDER_18,
        (p."B01001e7" + p."B01001e8" + p."B01001e9" + p."B01001e10" + p."B01001e11" + p."B01001e12" + COALESCE(p."B01001e31",0) + COALESCE(p."B01001e32",0) + COALESCE(p."B01001e33",0) + COALESCE(p."B01001e34",0) + COALESCE(p."B01001e35",0) + COALESCE(p."B01001e36",0)) AS POP_18_TO_34,
        (p."B01001e13" + p."B01001e14" + p."B01001e15" + p."B01001e16" + p."B01001e17" + COALESCE(p."B01001e37",0) + COALESCE(p."B01001e38",0) + COALESCE(p."B01001e39",0) + COALESCE(p."B01001e40",0) + COALESCE(p."B01001e41",0)) AS POP_35_TO_54,
        (p."B01001e18" + p."B01001e19" + p."B01001e20" + p."B01001e21" + COALESCE(p."B01001e42",0) + COALESCE(p."B01001e43",0) + COALESCE(p."B01001e44",0) + COALESCE(p."B01001e45",0)) AS POP_55_TO_69,
        (p."B01001e22" + p."B01001e23" + p."B01001e24" + p."B01001e25" + COALESCE(p."B01001e46",0) + COALESCE(p."B01001e47",0) + COALESCE(p."B01001e48",0) + COALESCE(p."B01001e49",0)) AS POP_70_PLUS,
        r."B03002e3" AS WHITE_NON_HISPANIC,
        r."B03002e4" AS BLACK_NON_HISPANIC,
        r."B03002e5" AS NATIVE_AMERICAN_NON_HISPANIC,
        r."B03002e6" AS ASIAN_NON_HISPANIC,
        r."B03002e7" AS PACIFIC_ISLANDER_NON_HISPANIC,
        r."B03002e12" AS HISPANIC_LATINO
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B01" p
    LEFT JOIN US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B03" r
        ON p.CENSUS_BLOCK_GROUP = r.CENSUS_BLOCK_GROUP
)
SELECT
    f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(c.TOTAL_POPULATION) AS TOTAL_POPULATION,
    SUM(c.MALE_POPULATION) AS MALE_POPULATION,
    SUM(c.FEMALE_POPULATION) AS FEMALE_POPULATION,
    SUM(c.POP_UNDER_18) AS POP_UNDER_18,
    SUM(c.POP_18_TO_34) AS POP_18_TO_34,
    SUM(c.POP_35_TO_54) AS POP_35_TO_54,
    SUM(c.POP_55_TO_69) AS POP_55_TO_69,
    SUM(c.POP_70_PLUS) AS POP_70_PLUS,
    SUM(c.WHITE_NON_HISPANIC) AS WHITE_NON_HISPANIC,
    SUM(c.BLACK_NON_HISPANIC) AS BLACK_NON_HISPANIC,
    SUM(c.NATIVE_AMERICAN_NON_HISPANIC) AS NATIVE_AMERICAN_NON_HISPANIC,
    SUM(c.ASIAN_NON_HISPANIC) AS ASIAN_NON_HISPANIC,
    SUM(c.PACIFIC_ISLANDER_NON_HISPANIC) AS PACIFIC_ISLANDER_NON_HISPANIC,
    SUM(c.HISPANIC_LATINO) AS HISPANIC_LATINO
FROM combined c
JOIN fips f ON c.STATE_FIPS = f.STATE_FIPS AND c.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- V_INCOME: Household income by state and county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_INCOME AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
income_dist AS (
    SELECT
        LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS,
        SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "B19001e1" AS TOTAL_HOUSEHOLDS,
        "B19001e2" AS HH_UNDER_10K,
        ("B19001e3" + "B19001e4" + "B19001e5") AS HH_10K_TO_24K,
        ("B19001e6" + "B19001e7" + "B19001e8" + "B19001e9" + "B19001e10") AS HH_25K_TO_49K,
        ("B19001e11" + "B19001e12" + "B19001e13") AS HH_50K_TO_99K,
        ("B19001e14" + "B19001e15" + "B19001e16") AS HH_100K_TO_199K,
        "B19001e17" AS HH_200K_PLUS,
        "B19013e1" AS MEDIAN_HOUSEHOLD_INCOME,
        "B19301e1" AS PER_CAPITA_INCOME
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B19"
)
SELECT
    f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(d.TOTAL_HOUSEHOLDS) AS TOTAL_HOUSEHOLDS,
    SUM(d.HH_UNDER_10K) AS HH_UNDER_10K,
    SUM(d.HH_10K_TO_24K) AS HH_10K_TO_24K,
    SUM(d.HH_25K_TO_49K) AS HH_25K_TO_49K,
    SUM(d.HH_50K_TO_99K) AS HH_50K_TO_99K,
    SUM(d.HH_100K_TO_199K) AS HH_100K_TO_199K,
    SUM(d.HH_200K_PLUS) AS HH_200K_PLUS,
    ROUND(AVG(d.MEDIAN_HOUSEHOLD_INCOME), 0) AS AVG_MEDIAN_HOUSEHOLD_INCOME,
    ROUND(AVG(d.PER_CAPITA_INCOME), 0) AS AVG_PER_CAPITA_INCOME
FROM income_dist d
JOIN fips f ON d.STATE_FIPS = f.STATE_FIPS AND d.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- V_HOUSING: Housing units and values by state and county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_HOUSING AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
housing AS (
    SELECT
        LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS,
        SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "B25001e1" AS TOTAL_HOUSING_UNITS,
        "B25003e2" AS OWNER_OCCUPIED,
        "B25003e3" AS RENTER_OCCUPIED,
        "B25077e1" AS MEDIAN_HOME_VALUE
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B25"
)
SELECT
    f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(h.TOTAL_HOUSING_UNITS) AS TOTAL_HOUSING_UNITS,
    SUM(h.OWNER_OCCUPIED) AS OWNER_OCCUPIED_UNITS,
    SUM(h.RENTER_OCCUPIED) AS RENTER_OCCUPIED_UNITS,
    ROUND(AVG(h.MEDIAN_HOME_VALUE), 0) AS AVG_MEDIAN_HOME_VALUE
FROM housing h
JOIN fips f ON h.STATE_FIPS = f.STATE_FIPS AND h.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- V_EDUCATION: Educational attainment (25+) by state and county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_EDUCATION AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
edu AS (
    SELECT
        LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS,
        SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "B15003e1" AS TOTAL_POP_25_PLUS,
        ("B15003e2" + "B15003e3" + "B15003e4" + "B15003e5" + "B15003e6" + "B15003e7" + "B15003e8" + "B15003e9" + "B15003e10" + "B15003e11" + "B15003e12" + "B15003e13" + "B15003e14" + "B15003e15" + "B15003e16") AS LESS_THAN_HIGH_SCHOOL,
        ("B15003e17" + "B15003e18") AS HIGH_SCHOOL_OR_GED,
        ("B15003e19" + "B15003e20") AS SOME_COLLEGE,
        "B15003e21" AS ASSOCIATES_DEGREE,
        "B15003e22" AS BACHELORS_DEGREE,
        "B15003e23" AS MASTERS_DEGREE,
        ("B15003e24" + "B15003e25") AS PROFESSIONAL_OR_DOCTORATE
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B15"
)
SELECT
    f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(e.TOTAL_POP_25_PLUS) AS TOTAL_POP_25_PLUS,
    SUM(e.LESS_THAN_HIGH_SCHOOL) AS LESS_THAN_HIGH_SCHOOL,
    SUM(e.HIGH_SCHOOL_OR_GED) AS HIGH_SCHOOL_OR_GED,
    SUM(e.SOME_COLLEGE) AS SOME_COLLEGE,
    SUM(e.ASSOCIATES_DEGREE) AS ASSOCIATES_DEGREE,
    SUM(e.BACHELORS_DEGREE) AS BACHELORS_DEGREE,
    SUM(e.MASTERS_DEGREE) AS MASTERS_DEGREE,
    SUM(e.PROFESSIONAL_OR_DOCTORATE) AS PROFESSIONAL_OR_DOCTORATE
FROM edu e
JOIN fips f ON e.STATE_FIPS = f.STATE_FIPS AND e.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- V_EMPLOYMENT: Labor force by state and county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_EMPLOYMENT AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
emp AS (
    SELECT
        LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS,
        SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "B23025e1" AS POP_16_PLUS,
        "B23025e2" AS IN_LABOR_FORCE,
        "B23025e4" AS EMPLOYED,
        "B23025e5" AS UNEMPLOYED,
        "B23025e6" AS ARMED_FORCES,
        "B23025e7" AS NOT_IN_LABOR_FORCE
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B23"
)
SELECT
    f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(e.POP_16_PLUS) AS POP_16_PLUS,
    SUM(e.IN_LABOR_FORCE) AS IN_LABOR_FORCE,
    SUM(e.EMPLOYED) AS EMPLOYED,
    SUM(e.UNEMPLOYED) AS UNEMPLOYED,
    SUM(e.ARMED_FORCES) AS ARMED_FORCES,
    SUM(e.NOT_IN_LABOR_FORCE) AS NOT_IN_LABOR_FORCE,
    ROUND(SUM(e.UNEMPLOYED) * 100.0 / NULLIF(SUM(e.IN_LABOR_FORCE), 0), 2) AS UNEMPLOYMENT_RATE,
    ROUND(SUM(e.IN_LABOR_FORCE) * 100.0 / NULLIF(SUM(e.POP_16_PLUS), 0), 2) AS LABOR_FORCE_PARTICIPATION_RATE
FROM emp e
JOIN fips f ON e.STATE_FIPS = f.STATE_FIPS AND e.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- V_STATE_SUMMARY: Quick state-level population rollup
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_SUMMARY AS
SELECT
    STATE_NAME, STATE_FIPS,
    SUM(TOTAL_POPULATION) AS TOTAL_POPULATION,
    SUM(MALE_POPULATION) AS MALE_POPULATION,
    SUM(FEMALE_POPULATION) AS FEMALE_POPULATION,
    SUM(POP_UNDER_18) AS POP_UNDER_18,
    SUM(POP_18_TO_34) AS POP_18_TO_34,
    SUM(POP_35_TO_54) AS POP_35_TO_54,
    SUM(POP_55_TO_69) AS POP_55_TO_69,
    SUM(POP_70_PLUS) AS POP_70_PLUS,
    SUM(WHITE_NON_HISPANIC) AS WHITE_NON_HISPANIC,
    SUM(BLACK_NON_HISPANIC) AS BLACK_NON_HISPANIC,
    SUM(ASIAN_NON_HISPANIC) AS ASIAN_NON_HISPANIC,
    SUM(HISPANIC_LATINO) AS HISPANIC_LATINO
FROM V_POPULATION
GROUP BY STATE_NAME, STATE_FIPS;

------------------------------------------------------------
-- V_STATE_INCOME: State-level income summary (one row per state)
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_INCOME AS
SELECT
    STATE_NAME,
    STATE_FIPS,
    SUM(TOTAL_HOUSEHOLDS) AS TOTAL_HOUSEHOLDS,
    SUM(HH_UNDER_10K) AS HH_UNDER_10K,
    SUM(HH_10K_TO_24K) AS HH_10K_TO_24K,
    SUM(HH_25K_TO_49K) AS HH_25K_TO_49K,
    SUM(HH_50K_TO_99K) AS HH_50K_TO_99K,
    SUM(HH_100K_TO_199K) AS HH_100K_TO_199K,
    SUM(HH_200K_PLUS) AS HH_200K_PLUS,
    ROUND(AVG(NULLIF(AVG_MEDIAN_HOUSEHOLD_INCOME, 0)), 0) AS MEDIAN_HOUSEHOLD_INCOME,
    ROUND(AVG(NULLIF(AVG_PER_CAPITA_INCOME, 0)), 0) AS PER_CAPITA_INCOME
FROM V_INCOME
GROUP BY STATE_NAME, STATE_FIPS;

------------------------------------------------------------
-- V_STATE_EMPLOYMENT: State-level employment summary (one row per state)
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_EMPLOYMENT AS
SELECT
    STATE_NAME,
    STATE_FIPS,
    SUM(POP_16_PLUS) AS POP_16_PLUS,
    SUM(IN_LABOR_FORCE) AS IN_LABOR_FORCE,
    SUM(EMPLOYED) AS EMPLOYED,
    SUM(UNEMPLOYED) AS UNEMPLOYED,
    SUM(ARMED_FORCES) AS ARMED_FORCES,
    SUM(NOT_IN_LABOR_FORCE) AS NOT_IN_LABOR_FORCE,
    ROUND(SUM(UNEMPLOYED) * 100.0 / NULLIF(SUM(IN_LABOR_FORCE), 0), 2) AS UNEMPLOYMENT_RATE,
    ROUND(SUM(IN_LABOR_FORCE) * 100.0 / NULLIF(SUM(POP_16_PLUS), 0), 2) AS LABOR_FORCE_PARTICIPATION_RATE
FROM V_EMPLOYMENT
GROUP BY STATE_NAME, STATE_FIPS;

------------------------------------------------------------
-- V_STATE_EDUCATION: State-level education summary (one row per state)
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_EDUCATION AS
SELECT
    STATE_NAME,
    STATE_FIPS,
    SUM(TOTAL_POP_25_PLUS) AS TOTAL_POP_25_PLUS,
    SUM(LESS_THAN_HIGH_SCHOOL) AS LESS_THAN_HIGH_SCHOOL,
    SUM(HIGH_SCHOOL_OR_GED) AS HIGH_SCHOOL_OR_GED,
    SUM(SOME_COLLEGE) AS SOME_COLLEGE,
    SUM(ASSOCIATES_DEGREE) AS ASSOCIATES_DEGREE,
    SUM(BACHELORS_DEGREE) AS BACHELORS_DEGREE,
    SUM(MASTERS_DEGREE) AS MASTERS_DEGREE,
    SUM(PROFESSIONAL_OR_DOCTORATE) AS PROFESSIONAL_OR_DOCTORATE,
    ROUND(SUM(BACHELORS_DEGREE) * 100.0 / NULLIF(SUM(TOTAL_POP_25_PLUS), 0), 1) AS PCT_BACHELORS,
    ROUND((SUM(BACHELORS_DEGREE) + SUM(MASTERS_DEGREE) + SUM(PROFESSIONAL_OR_DOCTORATE)) * 100.0 / NULLIF(SUM(TOTAL_POP_25_PLUS), 0), 1) AS PCT_COLLEGE_OR_HIGHER
FROM V_EDUCATION
GROUP BY STATE_NAME, STATE_FIPS;

------------------------------------------------------------
-- V_STATE_HOUSING: State-level housing summary (one row per state)
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_HOUSING AS
SELECT
    STATE_NAME,
    STATE_FIPS,
    SUM(TOTAL_HOUSING_UNITS) AS TOTAL_HOUSING_UNITS,
    SUM(OWNER_OCCUPIED_UNITS) AS OWNER_OCCUPIED_UNITS,
    SUM(RENTER_OCCUPIED_UNITS) AS RENTER_OCCUPIED_UNITS,
    ROUND(SUM(OWNER_OCCUPIED_UNITS) * 100.0 / NULLIF(SUM(OWNER_OCCUPIED_UNITS) + SUM(RENTER_OCCUPIED_UNITS), 0), 1) AS HOMEOWNERSHIP_RATE,
    ROUND(AVG(NULLIF(AVG_MEDIAN_HOME_VALUE, 0)), 0) AS MEDIAN_HOME_VALUE
FROM V_HOUSING
GROUP BY STATE_NAME, STATE_FIPS;
